### ISSUE TITLE
Connection to 0.tcp.ngrok.io closed.

### ISSUE THREAD

**Issue by BuiNgocHai** [lamhoangtung/ssh-kaggle-kernel-setup#1]
Hi.
I have ssh to set up kernel kernel, but have lost the connection after a few minutes
![image](https://user-images.githubusercontent.com/38074499/61492919-8d4c5500-a9dc-11e9-9772-aac68c90f75d.png)

**Comment by lamhoangtung** [comment]
Hi, free ngrok account tend to cause this problem in a while. A simple reconnect will get you back to the server. 
You should use tmux on the server to keep whatever you are doing ;)
