### ISSUE TITLE
When code running it says Canceled

### ISSUE THREAD

**Issue by banditnew** [lamhoangtung/ssh-kaggle-kernel-setup#3]
Everything ok.Ngrok ip coming.But in 10 seconds says canceled.
is this code still working?

**Comment by kpei** [comment]
just tried this and i got the same issue

```
Your notebook has been stopped by your request. If you just changed settings please wait while we reconfigure and restart your session.
```

**Comment by HarikrishnanBalagopal** [comment]
I am getting the same crash. Can you report this on the front page README.md?
Put a big warning sign that Kaggle no longer allows this.

**Comment by SoniCoder** [comment]
Yeah facing same problem ... please drop this repo in maintenance mode so that people don't get misguided

**Comment by tonyngmk** [comment]
Same here, notebook automatically crashes/die when tunnel to SSH is created. Hope someone comes up with a solution

**Comment by Manjeets666** [comment]
Facing this problem while ssh -
**kex_exchange_identification:** read: Connection reset by peer

**Comment by snapp1** [comment]
Seems like this hole was fixed by Kaggle. We can't do it anymore

**Comment by Manjeets666** [comment]
Oh i see. Any alternative to this?

**Comment by lamhoangtung** [comment]
Sorry for the late reply. I will put a notice that Kaggle no longer allow Ngrok tuneling in the README of this repo
