### ISSUE TITLE
SSH Connect failed 

### ISSUE THREAD

**Issue by linlih** [lamhoangtung/ssh-kaggle-kernel-setup#4]
ssh_exchange_identification: Connection closed by remote host

![image](https://user-images.githubusercontent.com/35171741/102688151-a4c1ea00-422f-11eb-96a6-6aa40df2c493.png)

**Comment by lamhoangtung** [comment]
Sorry for the late reply. I will put a notice that Kaggle no longer allow Ngrok tuneling in the README of this repo
